### PR TITLE
Add SAX messages bundle for XML parser to fix missing resource exception

### PR DESCRIPTION
**Pull request by sshark**
This should fix the MissingResourceException caused by some of the photos. The only way to be certain is to test more photos and fix them along the way.

### CODE REVIEW

**Comment by AlexITC** [comment]
Thanks, I'll try it soon with my photos and get back to you.

**Comment by sshark** [comment]
You can remove `GenerateNativeReflectionConfig.scala` because GraalVM has a tool called tracing agent to generate the required reflection configuration, https://medium.com/graalvm/introducing-the-tracing-agent-simplifying-graalvm-native-image-configuration-c3b56c486271

**Comment by AlexITC** [comment]
I'm aware of the agent but found it simpler to just include everything, I'm still willing to try it with the 10 year photo library I have.

**Comment by AlexITC** [comment]
I was finally able to try this, thanks for your patience.

Unfortunately, we can't get out of all metadata-extractor classes that are already in master, for example, I got this exception while trying with another file:

```
java.lang.RuntimeException: java.lang.InstantiationException: Type `com.drew.metadata.exif.makernotes.SonyType6MakernoteDirectory` can not be instantiated reflectively as it does not have a no-parameter constructor or the no-parameter constructor has not been added explicitly to the native image.
```

I'll try to do some tweaks to the changes before merging.

**Comment by AlexITC** [comment]
Merged manually at ba6b0e107db4eec1ec74f7a8261b0f1cce956667.

After including this PR, my test case work on most photos, 8 are still failing from more than 5k, it's a considerable improvement.

Thanks!

**Comment by AlexITC** [comment]
ignore my previous numbers, the 8 failing files are non-photos, all my test data is being handled properly now.

**Pull request closed without merging**
