### PR TITLE
Includes reflection classes to native image build

### PR DESCRIPTION
**Pull request by sshark**
A rough configuration for adding reflection classes to the native image build.

### CODE REVIEW

**Comment by AlexITC** [comment]
Unfortunately, that's not enough, I tried locally, and got another reflexion related error:

```
java.lang.ExceptionInInitializerError
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:290)
	at java.lang.Class.ensureInitialized(DynamicHub.java:499)
	at com.drew.metadata.exif.ExifTiffHandler.getReaderString(ExifTiffHandler.java:445)
	at com.drew.metadata.exif.ExifTiffHandler.processMakernote(ExifTiffHandler.java:463)
	at com.drew.metadata.exif.ExifTiffHandler.customProcessTag(ExifTiffHandler.java:207)
	at com.drew.imaging.tiff.TiffReader.processIfd(TiffReader.java:220)
	at com.drew.imaging.tiff.TiffReader.processIfd(TiffReader.java:214)
	at com.drew.imaging.tiff.TiffReader.processTiff(TiffReader.java:78)
	at com.drew.metadata.exif.ExifReader.extract(ExifReader.java:94)
	at com.drew.metadata.exif.ExifReader.extract(ExifReader.java:84)
	at com.drew.metadata.exif.ExifReader.readJpegSegments(ExifReader.java:63)
	at com.drew.imaging.jpeg.JpegMetadataReader.processJpegSegmentData(JpegMetadataReader.java:134)
	at com.drew.imaging.jpeg.JpegMetadataReader.process(JpegMetadataReader.java:126)
	at com.drew.imaging.jpeg.JpegMetadataReader.readMetadata(JpegMetadataReader.java:77)
	at com.drew.imaging.jpeg.JpegMetadataReader.readMetadata(JpegMetadataReader.java:84)
	at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:146)
	at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:124)
	at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:204)
	at net.wiringbits.myphototimeline.MetadataCreatedOnTag$.f$2(MetadataCreatedOnTag.scala:31)
	at net.wiringbits.myphototimeline.MetadataCreatedOnTag$.getCreationDate(MetadataCreatedOnTag.scala:45)
	at net.wiringbits.myphototimeline.FileOrganizerService$.$anonfun$load$1(FileOrganizerService.scala:37)
	at scala.collection.immutable.ArraySeq.$anonfun$map$1(ArraySeq.scala:71)
	at scala.collection.immutable.ArraySeq.$anonfun$map$1$adapted(ArraySeq.scala:71)
	at scala.collection.immutable.ArraySeq$.tabulate(ArraySeq.scala:288)
	at scala.collection.immutable.ArraySeq$.tabulate(ArraySeq.scala:267)
	at scala.collection.ClassTagIterableFactory$AnyIterableDelegate.tabulate(Factory.scala:664)
	at scala.collection.immutable.ArraySeq.map(ArraySeq.scala:71)
	at scala.collection.immutable.ArraySeq.map(ArraySeq.scala:35)
	at net.wiringbits.myphototimeline.FileOrganizerService$.load(FileOrganizerService.scala:32)
	at net.wiringbits.myphototimeline.FileOrganizerTask.run(FileOrganizerTask.scala:35)
	at net.wiringbits.myphototimeline.CommandAppHelper$.run(CommandAppHelper.scala:107)
	at net.wiringbits.myphototimeline.Main$$anonfun$$lessinit$greater$1.apply(Main.scala:17)
	at net.wiringbits.myphototimeline.Main$$anonfun$$lessinit$greater$1.apply(Main.scala:16)
	at cats.SemigroupalArityFunctions.$anonfun$map3$1(SemigroupalArityFunctions.scala:45)
	at cats.data.Validated.ap(Validated.scala:182)
	at cats.data.ValidatedApplicative.ap(Validated.scala:527)
	at cats.data.ValidatedApplicative.ap(Validated.scala:520)
	at cats.ComposedApply.$anonfun$ap$2(Composed.scala:33)
	at cats.Monad.$anonfun$map$1(Monad.scala:16)
	at cats.instances.Function0Instances$$anon$4.$anonfun$flatMap$1(function.scala:75)
	at cats.instances.Function0Instances$$anon$4.$anonfun$flatMap$1(function.scala:75)
	at com.monovore.decline.Parser.evalResult(Parser.scala:30)
	at com.monovore.decline.Parser.consumeAll(Parser.scala:107)
	at com.monovore.decline.Parser.apply(Parser.scala:19)
	at com.monovore.decline.Command.parse(opts.scala:18)
	at com.monovore.decline.CommandApp.main(CommandApp.scala:52)
	at net.wiringbits.myphototimeline.Main.main(Main.scala)
Caused by: java.nio.charset.UnsupportedCharsetException: Cp1252
	at java.nio.charset.Charset.forName(Charset.java:529)
	at com.drew.lang.Charsets.<clinit>(Charsets.java:40)
	at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
	... 46 more
```

Thanks!

**Comment by sshark** [comment]
Do you use English only for your OS? I am using Windows 10 English only. Please try using plain characters for filenames.

**Comment by AlexITC** [comment]
Yes, I'm trying with a single file named `DSC01144.JPG`, I was looking for a way to force the whole library into the native package but I haven't found anything.

**Comment by AlexITC** [comment]
I have merged this manually at 048ea1f1eeeef4c8b39cb2ffdd7e651ffd537026, unfortunately, more work is required.

Thanks!

**Pull request closed without merging**
